# Generated by Django 6.0.1 on 2026-01-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_createsuperuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hashed_refresh_token",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Hashed Refresh Token",
            ),
        ),
    ]
