# Generated by Django 6.0.1 on 2026-01-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_hashed_refresh_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="hashed_refresh_token",
            new_name="refresh_token_hash",
        ),
        migrations.AddField(
            model_name="user",
            name="refresh_token_valid_until",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Refresh Token Valid Until",
            ),
        ),
    ]
