# Generated by Django 6.0.1 on 2026-01-10 10:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_rename_hashed_refresh_token_user_refresh_token_hash_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="refresh_token_hash",
        ),
        migrations.RemoveField(
            model_name="user",
            name="refresh_token_valid_until",
        ),
        migrations.CreateModel(
            name="RefreshSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("refresh_token_hash", models.CharField(max_length=128, unique=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("rotation_counter", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["user"], name="user_refres_user_id_3e23ed_idx"),
                    models.Index(fields=["expires_at"], name="user_refres_expires_54ecbe_idx"),
                ],
            },
        ),
    ]
