# Generated by Django 6.0.1 on 2026-01-10 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_remove_user_refresh_token_hash_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refreshsession",
            name="device_id",
        ),
    ]
